services:
    
    db:
      image: mongo
      container_name: trpcdb_container
      volumes:
        - ./server/src/scripts/mongo_init.js:/docker-entrypoint-initdb.d/1.js  
        - ./data/mongo:/data/db 
      ports:
        - "27017:27017" 
  
    server:
      container_name: server_container 
      build: ./server
      restart: always
      env_file:
      - ./.env
      environment:
        - MONGO_URL=${MONGO_URL}
      depends_on:
        - db    
      ports:
        - "3000:3000"

    client:
      container_name: client_container 
      build: ./client
      depends_on:
        - server
      ports:
       - "5173:5173"
